### ISSUE TITLE
页面隐藏的时候有没有释放监听

### ISSUE THREAD

**Issue by Blet** [ryouaki/mp-redux#1]
是每个页面都会监听事件吗，假如小程序的页面有10层，前面9层都要监听这个数据，但他们是onHide的状态，也会监听吗

**Comment by ryouaki** [comment]
我并没有做事件监听呀。。。。。。。。。何来释放呀。。。。。

**Comment by Blet** [comment]
或者说是订阅某个数据的变化呢，9个页面都订阅了这个数据，你是怎么通知他们更新的？

**Comment by ryouaki** [comment]
> 或者说是订阅某个数据的变化呢，9个页面都订阅了这个数据，你是怎么通知他们更新的？

看文章和代码呀，我已经解释的很清楚了。

**Comment by Blet** [comment]
劫持生命周期来做更新吗？

**Comment by ryouaki** [comment]
> 劫持生命周期来做更新吗？

对呀 (T_T), 因为他们的内部属性响应式都是通过劫持做的。我通过注册事件实现的话，就要麻烦很多，别人使用也要麻烦很多。所以。我就劫持了生命周期，并且注入了mapStoreToState来实现数据的映射绑定进行订阅。还注入了dispatch来实现发布。

具体可以看dispatch那里的实现。
